services:
  db:
    image: mysql:8.0
    # keep the db under the same directory as this file, inside db_data so it persists
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '++DATABASE_ROOT_PASSWORD++'
      MYSQL_DATABASE: '++DATABASE_NAME++'
      MYSQL_USER: '++DATABASE_USER++'
      MYSQL_PASSWORD: '++DATABASE_PASSWORD++'

  wordpress:
    depends_on:
      - db
    # image: wordpress:6.2.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    restart: always
    # env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: '++DATABASE_USER++'
      WORDPRESS_DB_PASSWORD: '++DATABASE_PASSWORD++'
      WORDPRESS_DB_NAME: '++DATABASE_NAME++'

volumes:
  db_data: {}
  wordpress_data: {}
